issue HELM-2
emc-mongoose/mongoose-helm-charts pull request #13
Opened 2019-09-03 13:17 UTC by veronikaKochugova

scenario support added

2019-09-03 17:49 UTC, akurilov requested changes

2019-09-03 17:49 UTC, akurilov commented on mongoose/templates/scenario-configmap.yaml
> +    {{ .Values.scenario }}
Missing newline

2019-09-04 10:37 UTC, akurilov commented on mongoose/templates/scenario-configmap.yaml
> +    {{ .Values.scenario }}
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2019-09-05 15:39 UTC, akurilov approved these changes

2019-09-06 09:01 UTC, akurilov commented
Need the readme note about how to use a custom scneario

2019-09-06 09:01 UTC, akurilov requested changes
Need the readme note about how to use a custom scneario

2019-09-06 12:44 UTC, akurilov approved these changes

2019-09-06 12:48 UTC, dadlex approved these changes

2019-09-10 11:31 UTC, merged